### ISSUE TITLE
Additional Paper for the Hallucination Benchmarks section

### ISSUE THREAD

**Issue by AtsuMiyai** [showlab/Awesome-MLLM-Hallucination#3]
Hello. Thanks for your comprehensive survey on MLLM's hallucination, which is really beneficial in this field. 

We published a paper that tackled a novel task called Unsolvable Problem Detection (UPD) for MLLM.
https://arxiv.org/abs/2403.20331

UPD examines the MLLM’s ability to withhold answers when faced with unsolvable problems. 
We also propose MM-UPD Bench and benchmark recent MLLMs with MM-UPD Bench. 

We consider the definition and practical evaluation of the specific UPD problem to provide a novel and important contribution to existing hallucination benchmarks.

Could you add our work to the Hallucination Benchmarks section?  
+ **Unsolvable Problem Detection** [Unsolvable Problem Detection: Evaluating Trustworthiness of Vision Language Models](https://arxiv.org/abs/2403.20331) (Mar. 29, 2024)
  [![arXiv](https://img.shields.io/badge/arXiv-b31b1b.svg)](https://arxiv.org/abs/2403.20331)
  [![Star](https://img.shields.io/github/stars/AtsuMiyai/UPD.svg?style=social&label=Star)](https://github.com/AtsuMiyai/UPD)

**Comment by JosephPai** [comment]
Hi, the paper has just been updated to the benchmark section.
Thanks for your interests!
