### ISSUE TITLE
Update RLAIF-V

### ISSUE THREAD

**Issue by yiranyyu** [showlab/Awesome-MLLM-Hallucination#4]
Hi, 

We have recently released our latest work, `RLAIF-V: Aligning MLLMs through Open-Source AI Feedback for Super GPT-4V Trustworthiness`, on [GitHub](https://github.com/RLHF-V/RLAIF-V) and [arXiv.](https://arxiv.org/abs/2405.17220). 

The [dataset](https://huggingface.co/datasets/openbmb/RLAIF-V-Dataset) was on HuggingFace Trending Top 2. We would be truly grateful if you could consider adding RLAIF-V to your collection.

Thank you for your support!

**Comment by TobiasLee** [comment]
Awesome job, RLAIF-V team @yiranyyu ! 

I would like to kindly ask if our Silkie (mentioned in the survey paper as reference [68] but not included in the repo) could be added to the list.

You can find the Silkie project page [here](https://vlf-silkie.github.io/), which includes the dataset, model weights, and code.

Additionally, we recently discovered a repository for performing RLHF with LMMs to reduce hallucinations: [VL-RLHF](https://github.com/TideDra/VL-RLHF), might be useful for people interested in this topic. 

Thank you!

**Comment by JosephPai** [comment]
Hi @yiranyyu @TobiasLee , thanks for the reminder.
These two papers have been added to the paper list.
Btw, the project page of Silkie is broken.

**Comment by TobiasLee** [comment]
Thanks for your timely efforts! Awesome project again! 

The URL https://vlf-silkie.github.io/ is good to me. It's a GitHub Page so you might encounter network proxy issues?
