### ISSUE TITLE
New paper for hallucination benchmarks

### ISSUE THREAD

**Issue by LFhase** [showlab/Awesome-MLLM-Hallucination#5]
Hi, thanks for curating and maintaining this amazing list of MLLM hallucination! We would like to contribute our work released a few months ago to this list:

+ **CounterAnimal** [Do CLIPs Always Generalize Better than ImageNet Models?](https://arxiv.org/abs/2404.13874) (Mar. 18, 2024)
  [![arXiv](https://img.shields.io/badge/arXiv-b31b1b.svg)](https://arxiv.org/abs/2403.11497)

We trace back the hallucination issue to the multimodal alignment in CLIPs, which are often incorporated as MLLM visual encoders. We find surprising phenomena that CLIPs demonstrate high vulnerability to the natural distribution shifts captured by CounterAnimal and perform even worse than previous ImageNet-based models. This issue further leads to severe hallucinations of MLLMs such as LlaVA and MiniGPT-4. 

BTW, we also released a project page with the link to our benchmark, and feel free to decide what is the best way to add/or not add it to the list : )
  [Page](https://counteranimal.github.io/)

Thank you very much!

**Comment by JosephPai** [comment]
Hi @LFhase , thanks for your interests in this repo.
I recently refactored this paper list a bit.
Your paper has been added to the section of Hallucination Evaluation & Analysis. Very interest work! Hope it helps.
