### ISSUE TITLE
Happy to contribute our recent work RITUAL! (Mitigating hallucinations in MLLMs)

### ISSUE THREAD

**Issue by sangminwoo** [showlab/Awesome-MLLM-Hallucination#6]
Hi @JosephPai,

Thank you for curating this fantastic survey repository!
Please consider adding our recent work to the list. We are happy to contribute!

**RITUAL: Random Image Transformations as a Universal Anti-hallucination Lever in LVLMs**
[[Paper](https://arxiv.org/abs/2405.17821) | [Code](https://github.com/sangminwoo/RITUAL) | [Project](https://sangminwoo.github.io/RITUAL/)]

In this work, we propose RITUAL, a straightforward, training-free method to enhance robustness against hallucinations in Large Vision-Language Models (LVLMs). RITUAL employs random image transformations to complement the original probability distribution, aiming to reduce the likelihood of hallucinatory visual explanations by exposing the model to a diverse range of visual scenarios.

Thank you!

**Comment by JosephPai** [comment]
Hi @sangminwoo ,
Thanks for your interests in this repo.
The paper has been added to the Hallucination Mitigation section according to its release date. Very interesting work!
