### ISSUE TITLE
Contribute our work on mitigating hallucination of MLLM

### ISSUE THREAD

**Issue by Ethanscuter** [showlab/Awesome-MLLM-Hallucination#7]
Hi [@JosephPai](https://github.com/JosephPai),

Thanks for your awesome repository, which serves as a great resource in this community.

Could you please consider adding our recent paper on ACL 2024 about multimodal hallucination?

[ICD: Mitigating Hallucinations in Large Vision-Language Models with Instruction Contrastive Decoding](https://arxiv.org/pdf/2403.18715) ACL 2024 Mar. 23, 2024

In this work, we analyze that both positive and negative prompts can amplify hallucinations and propose a training-free method called instruction contrastive decoding, which works on the fusion module.

Thank you!

**Comment by JosephPai** [comment]
Hi @Ethanscuter , your ICD paper is already in the paper list. Very interesting work!
Congrats for your paper acceptance! I will update the conference information.
