### ISSUE TITLE
Add Paper Request

### ISSUE THREAD

**Issue by Ruiyang-061X** [showlab/Awesome-MLLM-Hallucination#9]
Dear Repo Authors,

Thank you all for your valuable effort in curating research on MLLM hallucination! This repository is quite pioneering and impressively thorough!

We have recently released our latest work: "VL-Uncertainty: Detecting Hallucination in Large Vision-Language Models via Uncertainty Estimation".

- Paper Link: https://arxiv.org/abs/2411.11919
- Website: https://vl-uncertainty.github.io/
- Code: https://github.com/Ruiyang-061X/VL-Uncertainty

I was wondering if you could kindly consider adding our paper to your excellent repository. Thank you once again for your invaluable contributions to this field!

Best regards,
Ruiyang

**Comment by JosephPai** [comment]
Hi Ruiyang,

Congrats on your great work!
Your paper is now included in the paper list.

Best,
Zechen
